FORMAT: 1A
HOST: http://www.google.com

# KC Direct Messaging Platform
This document describes the API for Kimberley-Clark's *Direct Messaging Platform*.

## Platform Functionality

It allows the business to segment their database of *consumers*, and create & track new marketing *campaigns* or *programs* aimed at those segments.

Each campaign or program is allocated to a specific *brand*.
The business can have multiple brands, and brands can have multiple campaigns & programs.

----

The system also allows the business (read: Admin users) to assign *users* to brands.

These users can administrate their assigned brands' campaigns & programs, as well as administrate the database of users, but cannot (should not) be able to segment or edit users that have not been allocated to the user's assigned brand(s).


### Campaigns

Campaigns are...


### Programs

Programs are...

----

## API Ops & Response

### HTTP Operations

Operation  | ...
---------  | -----------
**POST**   | Add or Update values or objects
**GET**    | Retrieve values or objects
**DELETE** | Delete objects

### HTTP Response codes

 Code   | ...
------- | -----------
**200** | Ok. Request processed.
**201** | Created. The object has been created.
**202** | Request accepted. The request has been accepted for processing, but the processing has not been completed.
**400** | Malformed request.
**401** | Authentication failed.
**403** | The user is not allowed to register or login, or the object may not be created. This response code is typically caused by the user or object already existing in the database.
**404** | Resource not found.
**412** | Precondition Failed. The server does not meet one of the preconditions that the requester put on the request.
**500** | Internal server error.
**501** | Not Implemented. The server either does not recognise the request method, or it lacks the ability to fulfil the request. 
**503** | Service Temporarily Unavailable.

----

# End Points

Please note:

- All IDs (user, company, consumer, brand, etc) will be GUIDs to prevent ID spoofing.
- Delete functions do not remove data they simply flag (date) an item as deleted so as not to skew metrics and to keep an audit trail.

# Group Login

## Login [/login]

Atempt to log the user into the system

### Login [POST]
This resource has the following attributes:

- `Username`
- `Password`

+ Response 200

+ Response 401


# Group Company

## Company [/company/{companyId}]

+ Parameters 
    + companyId (string, required) ... The Company ID


### Create a Company [POST]
Please update field names

- `Company Id`
- `Name`

+ Response 200

### View a Company [GET]
Please update field names

- `Company Id`
- `Name`

+ Response 200

### Delete Company [DELETE]
Please update field names

- `Company Id`
- `Name`
+ Response 200

## Company Metrics [/company/metrics/{companyId}]
+ Parameters 
    + companyId (string, required) ... 

### View Company Metrics [GET]
Please update field names

- `Company Id`
- `Name`
- `Number of brands`
- `Number of users`
- `Number of subscribers`
- `Number of active campaigns`
- `Number of active programs`

+ Response 200

# Group Brand

## Brand [/brand/{brandId}]
+ Parameters 
    + brandId (string, required) ... 

### Create Brand[POST]
Please update field names

- `Brand Id`
- `Name`
+ Response 200

### View Brand[GET]
Please update field names

- `Brand Id`
- `Name`

+ Response 200

### Delete Brand[DELETE]
Please update field names

- `Brand Id`
- `Name`
+ Response 200

## Brand Metrics [/brand/metrics/{brandId}]
+ Parameters 
    + brandId (string, required) ... 

### View Brand Metrics [GET]
Please update field names

- `Brand Id`
- `Name`
- `Number of users`
- `Number of subscribers`
- `Number of incomplete subscribers` This will be calculated as a subscriber that does not have all the prerequisite data fields (see subscriber)
- `Number of active campaigns`
- `Number of pending campaigns`
- `Number of complete campaigns`
- `Number of active programs`
- `Number of pending programs`
- `Number of complete programs`
+ Response 200

# Group User
## User [/user/{userId}]

This is a user of the system (not a subscriber)!

+ Parameters 
    + userId (string, required, `1123`) ... User's ID in the DB

+ Model (application/hal+json)

    JSON representation of the User object
    
    + Body
    
        ```
        {
            "_links": {
                "self": { "href": "/user/1123" },
            },
            "id": "1123",
            "created_at": "2014-04-14T02:15:15Z",
            "last_active": "2014-04-14T02:15:15Z",
            "company": {
                "id": 123,
                "name": "Some company"
            },
            "brand": {
                "id": 234,
                "name": "Some brand"
            },
            "firstname": "Emmanuel",
            "lastname": "Matsiyana",
            "email": "email@blah.com",
            "mobile": "123456789",
            "country": {
                "name": "South Africa",
                "code": "ZA"
            },
            "language": {
                "name": "English",
                "code": "en"
            }
        }
        ```
        
### Create User [POST]
Please update field names

- `User Id`
- `Company Id`
- `Brand Id`
- `First name`
- `Last name`
- `Email address`
- `Mobile`
- `User company`
- `Last active`
- `Country code`

+ Response 200
[User][]

### View User [GET]
Please update field names

- `User Id`
- `Company Id`
- `Brand Id`
- `First name`
- `Last name`
- `Email address`
- `Mobile`
- `User company`
- `Last active`
- `Country code`

+ Response 200

    [User][]

### Delete User [DELETE]
Please update field names

- `User Id`
- `Company Id`
- `Brand Id`
- `First name`
- `Last name`
- `Email address`
- `Mobile`
- `User company`
- `Last active`
- `Country code`

+ Response 200

## User Metrics [/user/metrics/{userId}]
+ Parameters 
    + userId (string, required, `1123`) ... User's ID in the DB

### View User Metrics [GET]
Please update field names

- `User Id`
- `Company Id`
- `Brand Id`
- `First name`
- `Last name`
- `Email address`
- `Mobile`
- `User company`
- `Last active`
- `Country code`
- `language code`
- `Campaigns created`
- `Campaigns deleted`
- `Programs created`
- `Programs deleted`

+ Response 200

## Reset User Password [/user/password-reset/{userId}]
+ Parameters 
    + userId (string, required, `1123`) ... User's ID in the DB

### Reset Password [POST]
This will generate a single use password change token. The token should ideally be sent directly to
the user as part of a confirmation link.

+ Response 200

## Change User Password [/user/password-change/]

### Change Password [POST]

Please update field names

- `Token Id`
- `New Password`

+ Response 200

## User Messsaging [/user/message/{userId}]
+ Parameters 
    + userId (string, required, `1123`) ... User's ID in the DB

### Messaging [POST]
This will generate a single use password change token. The token should ideally be sent directly to
the user as part of a confirmation link.

Please update field names

- `Email title` (optional)
- `Email message` (optional)
- `SMS message` (optional)

+ Response 200

# Group Campaigns

## Campaign [/campaigns/{campaignId}]
+ Parameters 
    + campaignId (string, required) ... 

### Create Campaign [POST]

Please update field names

- `Campaign Id`
- `Company Id`
- `Brand Id`
- `Name`
- `Description`
- `Start date & time`
- `End date & time` (optional)
- `Activation channels`
- `Engagement channels`
- `SMS message` (optional)
- `SMS response message` (optional)
- `SMS opt-out` (optional)
- `Email Subject line` (optional)
- `View online text` (optional)
- `Unsubscribe text` (optional)
- `Status` (optional)

+ Response 200

### View Campaign [GET]

Please update field names

- `Campaign Id`
- `Company Id`
- `Brand Id`
- `Name`
- `Description`
- `Start date & time`
- `End date & time` (optional)
- `Activation channels`
- `Engagement channels`
- `SMS message` (optional)
- `SMS response message` (optional)
- `SMS opt-out` (optional)
- `Email Subject line` (optional)
- `View online text` (optional)
- `Unsubscribe text` (optional)
- `Status` (optional)
+ Response 200

### Delete Campaign [DELETE]

Please update field names

- `Campaign Id`
- `Company Id`
- `Brand Id`
- `Name`
- `Description`
- `Start date & time`
- `End date & time` (optional)
- `Activation channels`
- `Engagement channels`
- `SMS message` (optional)
- `SMS response message` (optional)
- `SMS opt-out`
- `Email Subject line` (optional)
- `View online text` (optional)
- `Unsubscribe text` (optional)
- `Status` (optional)
+ Response 200

## Campaign Assests [/campaigns/assets/{campaignId}]

Please update field names

- `Asset file`. A zip file containing all your email assets, the zip file must contain at least `email.htm`, `unsubscribe.htm` and preferably `email.txt` for the plain text version.
- Image assets should be packaged in the zip file in the root folder. The `unsubscribe.htm` is a page users will view when unsubscribing, and should contain your corporate identity.
- Files with the same name will be automatically overwritten.

+ Parameters 
    + campaignId (string, required) ... 


### View Campaign Assets [POST]

+ Response 200

### View Campaign Assets [GET]

+ Response 200

### View Campaign Assets [DELETE]

+ Response 200

## Campaign Subscriber [/campaigns/subscriber/{campaignId}]
+ Parameters 
    + campaignId (string, required) ... 

### Create Campaign Subscriber [POST]

Please update field names

- `Subscriber Id`

+ Response 200

### Delete Campaign Subscriber [DELETE]

Please update field names

- `Subscriber Id`
+ Response 200

## Campaign Subscribers [/campaigns/subscribers/{campaignId}]

This will add or remove multiple users to/from a campaign. A list of all currently assigned users may
also be retrieved. A subscriber will only ever be added to a campaign once.

+ Parameters 
    + campaignId (string, required) ... 


### Create Campaign Subscribers [POST]

Please update field names

- `Subscriber Id`

+ Response 200

### View Campaign Subscribers [GET]

Please update field names

- `Subscriber Id`
+ Response 200

### Delete Campaign Subscribers [DELETE]

Please update field names

- `Subscriber Id`
+ Response 200

## Campaign Metrics [/campaigns/metrics/{campaignId}]
+ Parameters 
    + campaignId (string, required) ... 

### View Campaign Metrics [GET]

Please update field names

- `Total sent`
- `Total bounced`
- `Total unique opens`
- `Total clicks`
- `Total unique clicks`
- `Total modified`
- `Total unsubscribed`
- `Total delivered`
- `Percentage bounced`
- `Percentage delivered`
- `Percentage opened`
- `Percentage clicked`
- `Percentage clicked to open`
- `Percentage modified`
- `Percentage unsubscribed`
- `SMSs sent`
- `SMSs bounced`
- `SMSs unsubscribed`
- `SMSs percentage bounced`
- `SMSs percentage unsubscribed`

+ Response 200

## Campaign Responses [/campaigns/responses/{campaignId}]
This will return the current metrics for a campaign.


+ Parameters
    + campaignId (string,required) ...

### View Campaign Responses [GET]

Please update field names

- `Date of response`
- `Type of response` (email, sms or USSD)
- `Consumer Id`
- `Response data` (this will include all fields captured for the subscriber

+ Response 200

# Group Programs

## Programs [/programs/{programId}]

+ Parameters
    + programId (string,required) ...

### Create a Program [POST]

Please update field names

- `Program Id`
- `Company Id`
- `Brand Id`
- `Name`
- `Description`
- `Start date & time`
- `End date & time (optional)`
- `Engagement channels`
- `SMS opt-out (optional)`
- `1Cadence field`
- `1Status (optional)`

+ Response  200

### View a Program [GET]

Please update field names

- `Program Id`
- `Company Id`
- `Brand Id`
- `Name`
- `Description`
- `Start date & time`
- `End date & time (optional)`
- `Engagement channels`
- `SMS opt-out (optional)`
- `1Cadence field`
- `1Status (optional)`

+ Response  200

### Delete a Program [DELETE]

Please update field names

- `Program Id`
- `Company Id`
- `Brand Id`
- `Name`
- `Description`
- `Start date & time`
- `End date & time (optional)`
- `Engagement channels`
- `SMS opt-out (optional)`
- `1Cadence field`
- `1Status (optional)`

+ Response  200

## Programs Messaging [/programs/message/{programId}]

+ Parameters
    + programId (string,required) ...

### Create Programs Message [POST]

Please update fields

- `Message Id`
- `Program Id`
- `Message number`
- `Condition`

+ Response 200

### View Programs Message [GET]

Please update fields

- `Message Id`
- `Program Id`
- `Message number`
- `Condition`

+ Response 200

### Delete Programs Message [DELETE]

Please update fields

- `Message Id`
- `Program Id`
- `Message number`
- `Condition`

+ Response 200




## Programs SMS [/programs/assets/sms/{messageId}]
This adds a SMS message to a program message

 + Parameters 
     + messageId (string, required) ... 

### Create Program Message [POST]

- `SMS Message`
+ Response 200

### View Program Message [GET]

- `SMS Message`
+ Response 200

### Delete Program Message [DELETE]

- `SMS Message`
+ Response 200




## Programs Email Assets [/programs/assets/email/{messageId}]
This adds email assets to a program message

 + Parameters 
     + messageId (string, required) ... 

### Create Program Email Assets [POST]
- `Asset file`. A zip file containing all your email assets, the zip file must contain at least "email.htm"and preferably "email.txt" for the plain text version. Image assets should be packaged in the zip file in the root folder.
+ Response 200

### View Program Email Assets [GET]
- `Asset file`. A zip file containing all your email assets, the zip file must contain at least "email.htm"and preferably "email.txt" for the plain text version. Image assets should be packaged in the zip file in the root folder.
+ Response 200

### Delete Program Email Assets [DELETE]
- `Asset file`. A zip file containing all your email assets, the zip file must contain at least "email.htm"and preferably "email.txt" for the plain text version. Image assets should be packaged in the zip file in the root folder.
+ Response 200




## Programs Unsubscribe [/programs/unsubscribe/{programId}]
This adds an unsubscribe email message to a program

 + Parameters 
     + programId (string, required) ... 

### Unsubscribe from Program Email[POST]
- `Asset file`. A zip file containing all your email assets, the zip file must contain at least "email.htm"and preferably "unsubscribe.txt" for the plain text version. Image assets should be packaged in the zip file in the root folder.
+ Response 200

### View Unsubscribe from Program Email [GET]
- `Asset file`. A zip file containing all your email assets, the zip file must contain at least "email.htm"and preferably "unsubscribe.txt" for the plain text version. Image assets should be packaged in the zip file in the root folder.
+ Response 200

### Delete Unsubscribe from Program Email [DELETE]
- `Asset file`. A zip file containing all your email assets, the zip file must contain at least "email.htm"and preferably "unsubscribe.txt" for the plain text version. Image assets should be packaged in the zip file in the root folder.
+ Response 200




## Programs Subscriber [/programs/subscriber/{programId}]
This will add or remove a single user to a program. A subscriber will only ever be added to a program once.

 + Parameters 
     + programId (string, required) ... 

### Subscribe from Program[POST]
- `Subscriber Id`
+ Response 200

### Delete Subscribe from Program [DELETE]
- `Subscriber Id`
+ Response 200





## Programs Subscribers [/programs/subscribers/{programId}]
This will add or remove multiple users to/from a program. A list of all currently assigned users may also be retrieved. A subscriber will only ever be added to a program once.

 + Parameters 
     + programId (string, required) ... 

### Create Program Subscribers[POST]
- `Subscriber Id`
+ Response 200

### View Program Subscribers[GET]
- `Subscriber Id`
+ Response 200

### Delete Program Subscribers[DELETE]
- `Subscriber Id`
+ Response 200




## Program Metrics [/programs/metrics/{programId}]

This will retrieve the overall metrics for a program
+ Parameters
    + programId (string,required) ...

### View Program Metrics[GET]

- `Total sent`
- `Total bounced`
- `Total unique opens`
- `Total clicks`
- `Total unique clicks`
- `Total modified`
- `Total unsubscribed`
- `Total delivered`
- `Percentage bounced`
- `Percentage delivered`
- `Percentage opened`
- `Percentage clicked`
- `Percentage clicked to open`
- `Percentage modified`
- `Percentage unsubscribed`
- `SMSs sent`
- `SMSs bounced`
- `SMSs unsubscribed`
- `SMSs percentage bounced`
- `SMSs percentage unsubscribed`
+ Response 200





## Program Message Metrics [/programs/metrics/message/{programId}]

This will retrieve the metrics for an individual program message.
+ Parameters
    + programId (string,required) ...

### View Program Metrics[GET]
- `Total sent`
- `Total bounced`
- `Total unique opens`
- `Total clicks`
- `Total unique clicks`
- `Total modified`
- `Total unsubscribed`
- `Total delivered`
- `Percentage bounced`
- `Percentage delivered`
- `Percentage opened`
- `Percentage clicked`
- `Percentage clicked to open`
- `Percentage modified`
- `Percentage unsubscribed`
- `SMSs sent`
- `SMSs bounced`
- `SMSs unsubscribed`
- `SMSs percentage bounced`
- `SMSs percentage unsubscribed`

+ Response 200





# Group Consumer

## Consumer [/consumer/{consumerId}]

+ Parameters 
    + consumerId (string, required) ...

### Create a Consumer [POST]
- `Consumer Id`
- `First name`
- `Last name`
- `Email address`
- `Mobile`
- `Gender`
- `Title`
- `Date of birth`
- `Last active`
- `Country code`
- `Language code`
- `Status `

+ Response 200

### View a Consumer [GET]
- `Consumer Id`
- `First name`
- `Last name`
- `Email address`
- `Mobile`
- `Gender`
- `Title`
- `Date of birth`
- `Last active`
- `Country code`
- `Language code`
- `Status `

+ Response 200

### Delete a Consumer [DELETE]
- `Consumer Id`
- `First name`
- `Last name`
- `Email address`
- `Mobile`
- `Gender`
- `Title`
- `Date of birth`
- `Last active`
- `Country code`
- `Language code`
- `Status `

+ Response 200





## Consumer Engagement Campaigns [/consumer/engagement/campaigns/{consumerId}]
 + Parameters
     + consumerId (string, required) ...

### Create a Consumer engagement Campaign [POST]
- `Campaign Id`
- `Date of engagement`
- `Unsubscribed`

+ Response 200

### View a Consumer engagement Campaign [GET]
- `Campaign Id`
- `Date of engagement`
- `Unsubscribed`

+ Response 200

### Delete a Consumer engagement Campaign [DELETE]
- `Campaign Id`
- `Date of engagement`
- `Unsubscribed`

+ Response 200




## Consumer Fields [/consumer/{consumerId}/{fieldId}]
Allows you to add, read or delete any meta data for a single consumer specified by fieldname
 + Parameters
     + consumerId (string, required) ...

### Create a Consumer field [POST]
- `Consumer Id`
- `Field value`

+ Response 200

### View a Consumer field [GET]
- `Consumer Id`
- `Field value`

+ Response 200

### Delete a Consumer field [DELETE]
- `Consumer Id`
- `Field value`

+ Response 200







# Group Consumers

## Consumers Company List [/consumers/company/{companyId}]

+ Parameters
     + companyId (string, required) ...

### View Consumers By Company [GET]

- `Consumer Id`
- `First name`
- `Last name`
- `Email address`
- `Mobile`
- `Gender`
- `Title`
- `Date of birth`
- `Last active`
- `Country code`
- `Language code`
- `All existing consumer meta data`

+ Response 200





## Consumers Brand List [/consumers/brand/{brandId}]

+ Parameters
    + brandId (string, required) ...

### View Consumers By Brand [GET]

- `Consumer Id`
- `First name`
- `Last name`
- `Email address`
- `Mobile`
- `Gender`
- `Title`
- `Date of birth`
- `Last active`
- `Country code`
- `Language code`
- `All existing consumer meta data`

+ Response 200




## Consumers Campaign List [/consumers/campaign/{campaignId}]

+ Parameters
    + campaignId (string, required) ...

### View Consumers By Campaign [GET]

- `Consumer Id`
- `First name`
- `Last name`
- `Email address`
- `Mobile`
- `Gender`
- `Title`
- `Date of birth`
- `Last active`
- `Country code`
- `Language code`
- `All existing consumer meta data`

+ Response 200




## Consumers Program List [/consumers/program/{programId}]

+ Parameters
    + programId (string, required) ...

### View Consumers By Program [GET]

- `Consumer Id`
- `First name`
- `Last name`
- `Email address`
- `Mobile`
- `Gender`
- `Title`
- `Date of birth`
- `Last active`
- `Country code`
- `Language code`
- `All existing consumer meta data`

+ Response 200
