FORMAT: 1A
HOST: http://www.google.com

# KC DM
KCDM API is a ...

## HTTP Operations
Operation | Description
------------ | -------------
**POST** | Add or Update values or objects
**GET** | Retrieve values or objects
**DELETE** | Delete objects

## HTTP Response codes
 Code | Description
--------|-----------
**200** | Ok. Request processed.
**201** | Created. The object has been created.
**202** | Request accepted. The request has been accepted for processing, but the processing has not been completed.
**400** | Malformed request.
**401** | Authentication failed.
**403** | The user is not allowed to register or login, or the object may not be created. This response code is typically caused by the user or object already existing in the database.
**404** | Resource not found.
**412** | Precondition Failed. The server does not meet one of the preconditions that the requester put on the request.
**500** | Internal server error.
**501** | Not Implemented. The server either does not recognise the request method, or it lacks the ability to fulfil the request. 
**503** | Service Temporarily Unavailable.


## Login [/login]

Log the user into the system
### Login [POST]
This resource has the following attributes

- `Username` The Username of the user
- `Password` The Password of the user
+ Response 200

# Group Company
## Company [/company/{companyId}]
+ Parameters 
    + companyId (string, required) ... The Company ID


### Create a Company [POST]
Please update field names

- `Company Id`
- `Name`

+ Response 200

### View a Company [GET]
Please update field names

- `Company Id`
- `Name`
- `Number of brands`
- `Number of users`
- `Number of subscribers`
- `Number of active campaigns`
- `Number of active programs`

+ Response 200

### Delete Company [DELETE]
+ Response 200

## Company Metrics [/company/metrics/{companyId}]
+ Parameters 
    + companyId (string, required) ... 

### View Company Metrics [GET]
Please update field names

- `Company Id`
- `Name`
- `Number of brands`
- `Number of users`
- `Number of subscribers`
- `Number of active campaigns`
- `Number of active programs`

+ Response 200

# Group Brand

## Brand [/brand/{brandId}]
+ Parameters 
    + brandId (string, required) ... 

### Create Brand[POST]
+ Response 200

### View Brand[GET]

+ Response 200

### Delete Brand[DELETE]
+ Response 200

## Brand Metrics [/brand/metrics/{brandId}]
+ Parameters 
    + brandId (string, required) ... 

### View Brand Metrics [GET]
Please update field names

- `Brand Id`
- `Name`
- `Number of users`
- `Number of subscribers`
- `Number of incomplete subscribers` This will be calculated as a subscriber that does not have all the prerequisite data fields (see subscriber)
- `Number of active campaigns`
- `Number of pending campaigns`
- `Number of complete campaigns`
- `Number of active programs`
- `Number of pending programs`
- `Number of complete programs`
+ Response 200

# Group User
## User [/user/{userId}]

+ Parameters 
    + userId (string, required, `1123`) ... User's ID in the DB

+ Model (application/hal+json)

    JSON representation of the User object
    
    + Body
    
        ```
        {
            "_links": {
                "self": { "href": "/user/1123" },
            },
            "id": "1123",
            "created_at": "2014-04-14T02:15:15Z",
            "last_active": "2014-04-14T02:15:15Z",
            "company": {
                "id": 123,
                "name": "Some company"
            },
            "brand": {
                "id": 234,
                "name": "Some brand"
            },
            "firstname": "Emmanuel",
            "lastname": "Matsiyana",
            "email": "email@blah.com",
            "mobile": "123456789",
            "country": {
                "name": "South Africa",
                "code": "ZA"
            },
            "language": {
                "name": "English",
                "code": "en"
            }
        }
        ```
        
### Create User [POST]
Please update field names

- `Company Id`
- `Brand Id`
- `First name`
- `Last name`
- `Email address`
- `Mobile`
- `User company`
- `Last active`
- `Country code`
- `Language code`
+ Response 200
[User][]

### View User [GET]
Please update field names

- `Company Id`
- `Brand Id`
- `First name`
- `Last name`
- `Email address`
- `Mobile`
- `User company`
- `Last active`
- `Country code`
- `Language code`
+ Response 200

    [User][]

### Delete User [DELETE]
+ Response 200

## User Metrics [/user/metrics/{userId}]
+ Parameters 
    + userId (string, required, `1123`) ... User's ID in the DB

### View User Metrics [GET]
Please update field names

- `User Id`

+ Response 200

## Reset User Password [/user/password-reset/{userId}]
+ Parameters 
    + userId (string, required, `1123`) ... User's ID in the DB

### Reset Password [POST]
This will generate a single use password change token. The token should ideally be sent directly to
the user as part of a confirmation link.

+ Response 200

## User Messsaging [/user/message/{userId}]
+ Parameters 
    + userId (string, required, `1123`) ... User's ID in the DB

### Messaging [POST]
This will generate a single use password change token. The token should ideally be sent directly to
the user as part of a confirmation link.

Please update field names

- `Email title` (optional)
- `Email message` (optional)
- `SMS message` (optional)

+ Response 200

# Group Campaigns

## Campaign [/campaigns/{campaignId}]
+ Parameters 
    + campaignId (string, required) ... 

### Create Campaign [POST]

Please update field names

- `Campaign Id`
- `Company Id`
- `Brand Id`
- `Name`
- `Description`
- `Start date & time`
- `End date & time (optional)`
- `Activation channels`
- `Engagement channels`
- `SMS message (optional)`
- `SMS response message (optional)`
- `SMS opt-out (optional)`
- `Email Subject line (optional)`
- `View online text (optional)`
- `Unsubscribe text (optional)`
- `Status (optional)`
+ Response 200

### View Campaign [GET]

Please update field names

- `Campaign Id`
- `Company Id`
- `Brand Id`
- `Name`
- `Description`
- `Start date & time`
- `End date & time (optional)`
- `Activation channels`
- `Engagement channels`
- `SMS message (optional)`
- `SMS response message (optional)`
- `SMS opt-out (optional)`
- `Email Subject line (optional)`
- `View online text (optional)`
- `Unsubscribe text (optional)`
- `Status (optional)`
+ Response 200

### Delete Campaign [DELETE]

Please update field names

- `Campaign Id`
- `Company Id`
- `Brand Id`
- `Name`
- `Description`
- `Start date & time`
- `End date & time (optional)`
- `Activation channels`
- `Engagement channels`
- `SMS message (optional)`
- `SMS response message (optional)`
- `SMS opt-out (optional)`
- `Email Subject line (optional)`
- `View online text (optional)`
- `Unsubscribe text (optional)`
- `Status (optional)`
+ Response 200

## Campaign Assests [/campaigns/assets/{campaignId}]

### View Campaign Assets [GET]
- `Asset file`. A zip file containing all your email assets, the zip file must contain at least `email.htm`, `unsubscribe.htm` and preferably `email.txt` for the plain text version.
- Image assets should be packaged in the zip file in the root folder. The `unsubscribe.htm` is a page users will view when unsubscribing, and should contain your corporate identity.
- Files with the same name will be automatically overwritten.

+ Response 200

## Campaign Subscriber [/campaigns/subscriber/{campaignId}]

### Create Campaign Subscriber [POST]

Please update field names

- `Subscriber Id`

+ Response 200

### Delete Campaign Subscriber [DELETE]

Please update field names

- `Subscriber Id`
+ Response 200

## Campaign Subscribers [/campaigns/subscribers/{campaignId}]

This will add or remove multiple users to/from a campaign. A list of all currently assigned users may
also be retrieved. A subscriber will only ever be added to a campaign once.

### Create Campaign Subscribers [POST]

Please update field names

- `Subscriber Id`

+ Response 200

### View Campaign Subscribers [GET]

Please update field names

- `Subscriber Id`
+ Response 200

### Delete Campaign Subscribers [DELETE]

Please update field names

- `Subscriber Id`
+ Response 200

## Campaign Metrics [/campaigns/metrics/{campaignId}]

### View Campaign Metrics [GET]

Please update field names

- `Total sent`
- `Total bounced`
- `Total unique opens`
- `Total clicks`
- `Total unique clicks`
- `Total modified`
- `Total unsubscribed`
- `Total delivered`
- `Percentage bounced`
- `Percentage delivered`
- `Percentage opened`
- `Percentage clicked`
- `Percentage clicked to open`
- `Percentage modified`
- `Percentage unsubscribed`
- `SMSs sent`
- `SMSs bounced`
- `SMSs unsubscribed`
- `SMSs percentage bounced`
- `SMSs percentage unsubscribed`

+ Response 200

## Campaign Responses [/campaigns/responses/{campaignId}]

### View Campaign Responses [GET]

Please update field names

- `Date of response`
- `Type of response (email, sms or USSD)`
- `Consumer Id`
- `Response data` (this will include all fields captured for the subscriber

+ Response 200

# Group Programs